#pragma once
#include <string>
#include <regex>
#include <unordered_map>
#include <vector>

struct SwearEntry {
	std::string word;
	std::string pattern;
	int level;
	std::unordered_map<int, std::string> replacements;
};

std::vector<SwearEntry> swears = {
	// --- Level 1: Slurs against protected classes ---
	{"nigger", "\\bnigger", 1, {}},
	{"faggot", "\\bfaggot", 1, {}},
	{"nigga", "\\bnigga", 1, {}},
	{"jipped", "\\bjipped\\b", 1, {}},
	{"gypped", "\\bgypped\\b", 1, {}},
	{"peanut gallery", "\\bpeanut gallery\\b", 1, {}},
	{"peanutgallery", "\\bpeanutgallery\\b", 1, {}},
	{"tranny", "\\btranny\\b", 1, {}},
	{"hermaphrodite", "\\bhermaphrodite\\b", 1, {}},
	{"shemale", "\\bshemale\\b", 1, {}},
	{"heshe", "\\bheshe\\b", 1, {}},
	{"transgenderist", "\\btransgenderist\\b", 1, {}},
	{"transgenderism", "\\btransgenderism\\b", 1, {}},
	{"transsexualism", "\\btranssexualism\\b", 1, {}},
	{"transsexualist", "\\btranssexualist\\b", 1, {}},
	{"batty boy", "\\bbatty boy\\b", 1, {}},
	{"battyboy", "\\bbattyboy\\b", 1, {}},
	{"cocksucker", "\\bcocksucker\\b", 1, {}},
	{"gayrope", "\\bgayrope\\b", 1, {}},
	{"homintern", "\\bhomintern\\b", 1, {}},
	{"lesbo", "\\blesbo\\b", 1, {}},
	{"sissy", "\\bsissy\\b", 1, {}},
	{"gay rope", "\\bgay rope\\b", 1, {}},
	{"fence-sitter", "\\bfence-sitter\\b", 1, {}},
	{"fencesitter", "\\bfencesitter\\b", 1, {}},
	{"fence sitter", "\\bfence sitter\\b", 1, {}},
	{"bulldyke", "\\bbulldyke\\b", 1, {}},
	{"bull dyke", "\\bbull dyke\\b", 1, {}},
	{"bull-dyke", "\\bbull-dyke\\b", 1, {}},
	{"chickenhawk", "\\bchickenhawk\\b", 1, {}},
	{"chicken hawk", "\\bchicken hawk\\b", 1, {}},
	{"chicken-hawk", "\\bchicken-hawk\\b", 1, {}},
	{"chickenqueen", "\\bchickenqueen\\b", 1, {}},
	{"chicken queen", "\\bchicken queen\\b", 1, {}},
	{"chicken-queen", "\\bchicken-queen\\b", 1, {}},
	{"chickenplucker", "\\bchickenplucker\\b", 1, {}},
	{"chicken plucker", "\\bchicken plucker\\b", 1, {}},
	{"chicken-plucker", "\\bchicken-plucker\\b", 1, {}},
	{"cuntboy", "\\bcuntboy\\b", 1, {}},
	{"fag hag", "\\bfag hag\\b", 1, {}},
	{"wetback", "\\bwetback\\b", 1, {}},
	{"retard", "\\bretard", 1, {}},
	{"dyke", "\\bdyke\\b", 1, {{1,"lesbian"}}},
	{"nga", "\\bnga\\b", 1, {}},

	// --- Level 2: Severe sexual profanity ---
	{"sperm", "\\bsperm\\b", 2, {}},
	{"sex", "\\bsex\\b", 2, {}},
	{"sexy", "\\bsexy\\b", 2, {{2,"attractive"}}},
	{"semen", "\\bsemen\\b", 2, {}},
	{"jizz", "\\bjizz\\b", 2, {}},
	{"ejaculate", "\\bejaculate\\b", 2, {{2,"release"}}},
	{"jacking", "\\bjacking\\b", 2, {{2,"activity"}}},
	{"jerking", "\\bjerking\\b", 2, {{2,"activity"}}},
	{"edging", "\\bedging\\b", 2, {{2,"activity"}}},
	{"masturbat", "\\bmasturbat\\b", 2, {{2,"activity"}}},
	{"jacked", "\\bjacked\\b", 2, {{2,"excited"}}},
	{"jerked", "\\bjerked\\b", 2, {{2,"moved"}}},
	{"edged", "\\bedged\\b", 2, {{2,"tensed"}}},
	{"penis", "\\bpenis\\b", 2, {}},
	{"pussy", "\\bpussy\\b", 2, {}},
	{"cock", "\\bcock\\b", 2, {}},
	{"dick", "\\bdick\\b", 2, {{2,"jerk"}}},
	{"vajina", "\\bvajina\\b", 2, {}},
	{"vagina", "\\bvagina\\b", 2, {}},
	{"fingerbang", "\\bfingerbang\\b", 2, {{2,"act"}}},
	{"bang me", "\\bbang me\\b", 2, {}},
	{"bang you", "\\bbang you\\b", 2, {{}}},
	{"orgy", "\\borgy", 2, {{2,"group activity"}}},
	{"orgasm", "\\borgasm\\b", 2, {{2,"climax"}}},
	{"threesome", "\\bthreesome\\b", 2, {{2,"three-person activity"}}},
	{"foursome", "\\bfoursome\\b", 2, {{2,"four-person activity"}}},
	{"2g1c", "\\b2g1c\\b", 2, {{2,"explicit content"}}},
	{"whore", "\\bwhore\\b", 2, {{2,"jerk"}}},
	{"sluttiest", "\\bsluttiest\\b", 2, {{2,"coolest"}}},
	{"slutty", "\\bslutty\\b", 2, {{2,"cool"}}},
	{"slut", "\\bslut\\b", 2, {{2,"active"}}},
	{"cum", "\\bcum", 2, {}},
	{"serving cunt", "\\bserving cunt\\b", 2, {{2,"cooking"}}},
	{"serving cvnt", "\\bserving cvnt\\b", 2, {{2,"cooking"}}},
	{"cunt", "\\bcunt", 2, {{2,"jerk"}}},
	{"cvnt", "\\bcvnt", 2, {{2,"jerk"}}},
	{"twat", "\\btwat\\b", 2, {{2,"jerk"}} },

	// --- Level 3: Moderate sexual profanity ---
	{"fuck", "\\bfuck\\b", 3, {{3,"hell"}}},
	{"what the fuck", "\\bwhat the fuck\\b", 3, {{3,"what the hell"}}},
	{"fuckery", "\\bfuckery\\b", 3, {{3,"nonsense"}}},
	{"fucker", "\\bfucker", 3, {{3,"piece of shit"}, {4, "person"}}},
	{"fucking", "\\bfucking\\b", 3, {{3,"really"}}},
	{"fuckin", "\\bfuckin\\b", 3, {{3,"really"}}},
	{"fucked", "\\bfucked\\b", 3, {{3,"messed"}}},
	{"fucks", "\\bfucks\\b", 3, {{3,"issues"}}},
	{"fuk", "\\bfuk\\b", 3, {{3,"hek"}}},
	{"clusterfuck", "\\bclusterfuck\\b", 3, {{3,"mess"}}},
	{"crazy motherfucker", "\\bcrazy motherfucker\\b", 3, {{3,"crazy piece of shit"}, {4, "crazy person"}}},
	{"crazy fatherfucker", "\\bcrazy fatherfucker\\b", 3, {{3,"crazy piece of shit"}, {4, "crazy person"}}},
	{"crazy brotherfucker", "\\bcrazy brotherfucker\\b", 3, {{3,"crazy piece of shit"}, {4, "crazy person"}}},
	{"crazy sisterfucker", "\\bcrazy sisterfucker\\b", 3, {{3,"crazy piece of shit"}, {4, "crazy person"}}},
	{"motherfucker", "\\bmotherfucker", 3, {{3,"piece of shit"}}},
	{"fatherfucker", "\\bfatherfucker", 3, {{3,"piece of shit"}}},
	{"brotherfucker", "\\bbrotherfucker", 3, {{3,"piece of shit"}}},
	{"sisterfucker", "\\bsisterfucker", 3, {{3,"piece of shit"}}},

	// --- Level 4: Mild sexual profanity ---
	{"bitch", "\\bbitch\\b", 4, {{4,"jerk"}} },
	{"bitches", "\\bbitches\\b", 4, {{4,"jerks"}} },
	{"bitching", "\\bbitching\\b", 4, {{4,"complaining"}}},
	{"bitcher", "\\bbitcher\\b", 4, {{4,"complainer"}}},

	// --- Level 5: Excrement profanity ---
	{"a little chickenshit", "\\ba little chickenshit\\b", 5, {{5,"a little petty"}}},
	{"very chickenshit", "\\bvery chickenshit\\b", 5, {{5,"very petty"}}},
	{"too chickenshit", "\\btoo chickenshit\\b", 5, {{5,"too petty"}}},
	{"chickenshit", "\\bchickenshit\\b", 5, {{5,"crap"}}},
	{"asshead", "\\basshead\\b", 5, {{5,"jerk"}}},
	{"asshat", "\\basshat\\b", 5, {{5,"jerk"}}},
	{"asshole", "\\basshole\\b", 5, {{5,"jerk"}}},
	{"dipshit", "\\bdipshit\\b", 5, {{5,"idiot"}}},
	{"bullshitting", "\\bbullshitting\\b", 5, {{5,"playing with"}}},
	{"bullshit", "\\bbullshit", 5, {{5,"nonsense"}}},
	{"shit", "\\bshitt", 5, {{5,"crapp"}}},
	{"shit", "\\bshit", 5, {{5,"crap"}}},

	// --- Level 6: Religious and silly levels of profanity ---
	{"god damn", "\\bgod damn", 6, {{6,"darn"}}},
	{"damn", "\\bdamn", 6, {{6,"darn"}}},
	{"hell", "\\bhell\\b", 6, {{6,"heck"}}},
	{"crap", "\\bcrap\\b", 6, {{6,"poop"}}},
	{"crappy", "\\bcrappy\\b", 6, {{6,"muddy"}}},
	{"crappiest", "\\bcrappiest\\b", 6, {{6,"muddiest"}}},
	{"crapper", "\\bcrapper\\b", 6, {{6,"toilet"}}},
	{"craps", "\\bcraps\\b", 6, {{6,"poops"}}},
	{"ass", "\\bass\\b", 6, {{6,"tail"}} },
};
